language: R
cache: packages
sudo: false
use_bioc: true

os:
- linux
- osx

r:
- release
- devel

r_packages:
- mvtnorm
- gdata
- BiocManager
- DBI
- plogr
- RSQLite

bioc_packages:
- AnnotationDbi
- org.Hs.eg.db

r_build_args: "--html"

r_check_args: "--as-cran --timings"