language: R
cache: packages
sudo: false

os:
- linux
- osx

r:
- release
- devel

r_packages:
- mvtnorm
- gdata
- BiocManager

bioc_packages:
- org.Hs.eg.db

r_build_args: "--html"

r_check_args: "--as-cran --timings"